import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from src.parser.tool_parser import ParseResult


@dataclass
class Step:
    chat_completions: list[dict[str, str]] = field(default_factory=list)

    observation: Any = None
    action: Any = None
    model_response: str = ""
    model_output: "ModelOutput" = None  # noqa: F821
    info: dict = field(default_factory=dict)  # Store any additional info.

    # Parse result from tool parser (contains tool_calls and format_errors)
    # Used by reward shapers to compute format penalty without re-parsing
    parse_result: Optional["ParseResult"] = None

    # field below are filled by the engine
    reward: float = 0.0
    done: bool = False
    mc_return: float = 0.0

    # Compression support: for context consistency in training
    is_compression_boundary: bool = False  # True if this step triggers compression
    chat_completions_before_compression: list[dict[str, str]] = field(default_factory=list)  # Context before compression
    compression_summary: str = ""  # The summary generated by compression

    # Lossless compression support: for context alignment in PPO/GRPO
    chat_completions_at_generation: list[dict[str, str]] = field(default_factory=list)  # Context when model generated response (before retrieve)
    num_retrievals_in_step: int = 0  # Number of ReadExperience calls in this step
    num_compressions_in_step: int = 0  # Number of CompressExperience calls in this step
    retrieval_indices: list[str] = field(default_factory=list)  # DB indices that were retrieved
    context_length: int = 0  # Estimated context length in tokens at this step

    def to_dict(self) -> dict:
        return {
            "chat_completions": self.chat_completions,
            "observation": self.observation,
            "action": self.action,
            "model_response": self.model_response,
            "model_output": self.model_output.to_dict() if self.model_output is not None else None,
            "info": self.info,
            "reward": self.reward,
            "done": self.done,
            "mc_return": self.mc_return,
            "is_compression_boundary": self.is_compression_boundary,
            "chat_completions_before_compression": self.chat_completions_before_compression,
            "compression_summary": self.compression_summary,
            # Lossless compression fields
            "chat_completions_at_generation": self.chat_completions_at_generation,
            "num_retrievals_in_step": self.num_retrievals_in_step,
            "num_compressions_in_step": self.num_compressions_in_step,
            "retrieval_indices": self.retrieval_indices,
            "context_length": self.context_length,
            # Parse result for format penalty calculation
            "parse_result": self.parse_result.to_dict() if self.parse_result is not None else None,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Step":
        from src.engine.rollout import ModelOutput
        from src.parser.tool_parser import ParseResult

        parse_result_data = data.get("parse_result")
        parse_result = ParseResult.from_dict(parse_result_data) if parse_result_data is not None else None

        return cls(
            chat_completions=data["chat_completions"],
            observation=data["observation"],
            action=data["action"],
            model_response=data["model_response"],
            model_output=ModelOutput.from_dict(data["model_output"]) if data.get("model_output", None) is not None else None,
            info=data.get("info", {}),
            reward=data["reward"],
            done=data["done"],
            mc_return=data["mc_return"],
            is_compression_boundary=data.get("is_compression_boundary", False),
            chat_completions_before_compression=data.get("chat_completions_before_compression", []),
            # Lossless compression fields
            chat_completions_at_generation=data.get("chat_completions_at_generation", []),
            num_retrievals_in_step=data.get("num_retrievals_in_step", 0),
            num_compressions_in_step=data.get("num_compressions_in_step", 0),
            retrieval_indices=data.get("retrieval_indices", []),
            compression_summary=data.get("compression_summary", ""),
            context_length=data.get("context_length", 0),
            parse_result=parse_result,
        )


@dataclass
class Action:
    action: Any = None


@dataclass
class Trajectory:
    uid: str = field(default_factory=lambda: str(uuid.uuid4()))  # unique id to deduplicate on
    name: str = "agent"
    task: Any = None
    steps: list[Step] = field(default_factory=list)
    reward: float = 0.0
    info: dict = field(default_factory=dict)

    def to_dict(self):
        return {
            "uid": self.uid,
            "name": self.name,
            "task": self.task,
            "steps": [step.to_dict() for step in self.steps],
            "reward": float(self.reward),
            "info": self.info,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Trajectory":
        """Create Trajectory from dictionary, properly deserializing Step objects."""
        return cls(
            uid=data.get("uid", str(uuid.uuid4())),
            name=data["name"],
            task=data["task"],
            steps=[Step.from_dict(step_data) for step_data in data.get("steps", [])],
            reward=data["reward"],
            info=data.get("info", {}),
        )

    def is_cumulative(self) -> bool:
        """
        Returns True if for every step after the first, its chat_completions is an exact superset
        of the previous step's chat_completions (i.e., the previous chat_completions is a prefix).
        """
        prev = None
        for step in self.steps:
            if prev is not None:
                prev_cc = prev.chat_completions
                curr_cc = step.chat_completions
                if not (len(curr_cc) >= len(prev_cc) and curr_cc[: len(prev_cc)] == prev_cc):
                    return False
            prev = step
        return True

    def get_compression_stats(self) -> dict:
        """
        Returns statistics about compression boundaries in this trajectory.
        Useful for debugging and verification.
        """
        compression_steps = [i for i, step in enumerate(self.steps) if step.is_compression_boundary]
        stats = {
            "total_steps": len(self.steps),
            "compression_boundaries": len(compression_steps),
            "compression_step_indices": compression_steps,
            "has_compression": len(compression_steps) > 0,
        }

        # For each compression boundary, record context size changes
        if compression_steps:
            stats["compression_details"] = []
            for idx in compression_steps:
                step = self.steps[idx]
                detail = {
                    "step_idx": idx,
                    "context_before": len(step.chat_completions_before_compression),
                    "context_after": len(step.chat_completions),
                    "messages_removed": len(step.chat_completions_before_compression) - len(step.chat_completions),
                    "summary_length": len(step.compression_summary),
                }
                stats["compression_details"].append(detail)

        return stats


@dataclass
class Episode:
    id: str = ""  # rollout id e.g., task_id:rollout_idx
    task: Any = None
    termination_reason: "TerminationReason" = None  # noqa: F821
    is_correct: bool = False
    trajectories: list[Trajectory] = field(default_factory=list)
    metrics: dict = field(default_factory=dict)
    info: dict = field(default_factory=dict)

    def to_dict(self):
        return {
            "id": self.id,
            "task": self.task,
            "termination_reason": self.termination_reason.value if self.termination_reason is not None else None,
            "is_correct": bool(self.is_correct),
            "trajectories": [trajectory.to_dict() for trajectory in self.trajectories],
            "metrics": self.metrics,
            "info": self.info,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Episode":
        """Create Episode from dictionary, properly deserializing Trajectory objects."""
        from src.engine.termination import TerminationReason

        return cls(
            id=data["id"],
            task=data["task"],
            termination_reason=TerminationReason(data["termination_reason"]) if data.get("termination_reason") is not None else TerminationReason.UNKNOWN,
            is_correct=data["is_correct"],
            trajectories=[Trajectory.from_dict(trajectory_data) for trajectory_data in data["trajectories"]],
            metrics=data.get("metrics", {}),
            info=data.get("info", {}),
        )


class BaseAgent(ABC):
    @property
    def chat_completions(self) -> list[dict[str, str]]:
        """Converts agent's internal state into a list of OAI chat completions."""
        return []

    @property
    def trajectory(self) -> Trajectory:
        """Converts agent's internal state into a Trajectory object."""
        return Trajectory()

    def update_from_env(self, observation: Any, reward: float, done: bool, info: dict, **kwargs):
        """
        Updates the agent's internal state after an environment step.

        Args:
            observation (Any): The observation after stepping through environment.
            reward (float): The reward received after taking the action.
            done (bool): Whether the episode has ended due to termination.
            info (dict): Additional metadata from the environment.
        """
        raise NotImplementedError("Subclasses must implement this method if using AgentExecutionEngine")

    def update_from_model(self, response: str, **kwargs) -> Action:
        """
        Updates the agent's internal state after the model generates a response.

        Args:
            response (str): The response from the model.

        Returns:
            None
        """
        raise NotImplementedError("Subclasses must implement this method if using AgentExecutionEngine")

    @abstractmethod
    def reset(self):
        """
        Resets the agent's internal state, typically called at the beginning of a new episode.

        This function should clear any stored history or state information necessary
        for a fresh interaction.

        Returns:
            None
        """
        return

    def get_current_state(self) -> Step | None:
        """
        Returns the agent's current state as a dictionary.

        This method provides access to the agent's internal state at the current step,
        which can be useful for debugging, logging, or state management.

        Returns:
            Step: The agent's current state.
        """
        if not self.trajectory.steps:
            return None
        return self.trajectory.steps[-1]
